export const DOCUMENT_TYPES = {
  BOX_CONTENT_LABEL_OUTBOUND: 'BOX_CONTENT_LABEL_OUTBOUND',
  BOX_CONTENT_LABEL_SAMPLE: 'BOX_CONTENT_LABEL_SAMPLE',
  NON_ADR_DECLARATION: 'NON_ADR_DECLARATION',
  SHIPPING_LABEL_OUTBOUND: 'SHIPPING_LABEL_OUTBOUND',
  SHIPPING_LABEL_SAMPLE: 'SHIPPING_LABEL_SAMPLE',
  PACKING_LIST: 'PACKING_LIST',
  COMMERCIAL_INVOICE: 'COMMERCIAL_INVOICE',
  PROOF_OF_DELIVERY_OUTBOUND: 'PROOF_OF_DELIVERY_OUTBOUND',
  PROOF_OF_DELIVERY_SAMPLE: 'PROOF_OF_DELIVERY_SAMPLE',
} as const;

export const DOCUMENT_TYPE_LABELS: Record<string, string> = {
  BOX_CONTENT_LABEL_OUTBOUND: 'Box Content Label (Outbound)',
  BOX_CONTENT_LABEL_SAMPLE: 'Box Content Label (Sample)',
  NON_ADR_DECLARATION: 'Non-ADR Declaration',
  SHIPPING_LABEL_OUTBOUND: 'Shipping Label (Outbound)',
  SHIPPING_LABEL_SAMPLE: 'Shipping Label (Sample)',
  PACKING_LIST: 'Packing List',
  COMMERCIAL_INVOICE: 'Commercial Invoice',
  PROOF_OF_DELIVERY_OUTBOUND: 'Proof of Delivery (Outbound)',
  PROOF_OF_DELIVERY_SAMPLE: 'Proof of Delivery (Sample)',
};
